# Generated by Django 3.1.7 on 2021-03-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badword', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_column='title', unique=True)),
            ],
            options={
                'db_table': 'texts_klass',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
