# Generated by Django 3.1.7 on 2021-03-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badword', '0002_auto_20210313_0822'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='textmodel',
            table=None,
        ),
    ]
