# Generated by Django 3.1.7 on 2021-03-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badword', '0004_auto_20210313_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textmodel',
            options={'managed': True, 'verbose_name': 'Типы'},
        ),
        migrations.AlterField(
            model_name='textmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
