# Generated by Django 3.1.7 on 2021-03-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badword', '0005_auto_20210313_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textmodel',
            options={'managed': True, 'verbose_name': 'texts'},
        ),
    ]
