# Generated by Django 3.1.7 on 2021-03-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badword', '0006_auto_20210313_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmodel',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
